[package]
name = "hello-puppeteer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html-to-string-macro = "0.2.5"
puppeteer = { path = "../../Lib" }
smol = "1.3.0"
tracing-subscriber = "0.3.17"
